### ISSUE TITLE
 Missing Meta Data in Raw Dataset

### ISSUE THREAD

**Issue by qitianliang** [wz9619/MMPOI#1]
I have noticed that the raw dataset provided is missing the meta data. Could you please provide the corresponding collection method or the missing data? Thank you for your attention to this matter and for your assistance.

**Comment by qitianliang** [comment]
I've resolved the issue by referencing the example for collecting places' metadata available at [Foursquare Place Details API documentation](https://docs.foursquare.com/developer/reference/place-details).

**Comment by wangjunkaiy** [comment]
请问您找到了原始数据集中的元数据？是否可以分享一下，感谢您对此问题的关注和帮助。
